// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type InventoryItem struct {
	ID                uuid.UUID `json:"id"`
	ProductID         uuid.UUID `json:"product_id"`
	Quantity          int32     `json:"quantity"`
	ReservedQuantity  int32     `json:"reserved_quantity"`
	AvailableQuantity int32     `json:"available_quantity"`
	ReorderPoint      int32     `json:"reorder_point"`
	ReorderQuantity   int32     `json:"reorder_quantity"`
	StockStatus       string    `json:"stock_status"`
	LocationCode      string    `json:"location_code"`
	LastStockedAt     time.Time `json:"last_stocked_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type InventoryTransaction struct {
	ID           uuid.UUID      `json:"id"`
	ProductID    uuid.UUID      `json:"product_id"`
	Quantity     int32          `json:"quantity"`
	Type         string         `json:"type"`
	ReferenceID  sql.NullString `json:"reference_id"`
	Note         sql.NullString `json:"note"`
	PerformedBy  string         `json:"performed_by"`
	TransactedAt time.Time      `json:"transacted_at"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Product struct {
	ID          uuid.UUID      `json:"id"`
	Sku         string         `json:"sku"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Category    string         `json:"category"`
	Price       string         `json:"price"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
